{% set name = "geoarrow-pyarrow" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoarrow-pyarrow-{{ version }}.tar.gz
  sha256: 318b3bd42e865b7b2cd7bcb0947c4053f07be15296153c297e94150a4be7357e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geoarrow-c
    - pyarrow
    - python >=3.8
    - pyarrow-hotfix

test:
  imports:
    - geoarrow.pyarrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geoarrow/geoarrow-pyarrow
  summary: GeoArrow integration with pyarrow and pyarrow-based libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - paleolimbot
