{% set name = "geoarrow-pyarrow" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geoarrow-pyarrow-{{ version }}.tar.gz
  sha256: dec429fac397f6d3616e224b9cae6229dfcc1be3c279bbe304da55bbd26e0407

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - geoarrow-c
    - pyarrow
    - python >=3.8

test:
  imports:
    - geoarrow.pyarrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geoarrow/geoarrow-pyarrow
  summary: GeoArrow integration with pyarrow and pyarrow-based libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - paleolimbot
